---
- hosts: all

  tasks:
  - apt: update_cache=yes cache_valid_time=21600
  - apt: pkg=update-notifier-common
  - name: Upgrade Everything
    apt: upgrade=dist
  - apt: pkg=emacs23-nox
  - apt: pkg=curl
  - apt: pkg=ntp
  - apt: pkg=git
  - apt: pkg=linux-image-generic-lts-saucy
  - apt: pkg=linux-headers-generic-lts-saucy
  - apt: pkg=python-pip
  - apt: pkg=python-setuptools

  - name: check if a reboot is required
    shell: "[ -f /var/run/reboot-required ]"
    failed_when: False
    register: reboot_required
    changed_when: reboot_required.rc == 0
    notify: reboot

  handlers:
  - name: reboot
    command: /sbin/reboot

  - name: restartmysqld
    service: name=mysql state=restarted


