---
- hosts: compute01
  vars:
    MYSQL_ROOT: "{{ lookup('env','DB_ROOT') }}"
    GLANCE_DBPWD: "{{ lookup('env','GLANCE_DBPASS') }}"
    RABBIT_PWD: "{{ lookup('env','RABBIT_PASS') }}"
    GLANCE_PWD: "{{ lookup('env','GLANCE_PASS') }}"
    NOVA_DBPWD: "{{ lookup('env','NOVA_DBPASS') }}"
    NOVA_PWD: "{{ lookup('env','NOVA_PASS') }}"

  tasks:
  - apt: update_cache=yes cache_valid_time=21600

  - copy: src=compute01_files/compute_hosts dest=/etc/hosts
  - hostname: name=compute01
  - copy: src=ntp.conf dest=/etc/ntp.conf
  - service: name=ntp state=restarted

  - apt: pkg=python-mysqldb

  - apt: pkg=debconf-utils
  - shell: executable=/bin/bash debconf-set-selections <<< 'libguestfs0 libguestfs/update-appliance boolean true'
  - apt: pkg=python-guestfs

  - shell: creates=/root/.dpkg-statoverride dpkg-statoverride  --update --add root root 0644 /boot/vmlinuz-$(uname -r) && touch /root/.dpkg-statoverride
  - copy: src=compute01_files/statoverride dest=/etc/kernel/postinst.d/statoverride owner=root group=root mode=0755

  - apt: pkg=gcc
  - apt: pkg=python-dev
  - apt: pkg=libxml2-dev
  - apt: pkg=libxslt1-dev
  - apt: pkg=libffi-dev
  - command: creates=/root/nova git clone https://github.com/openstack/nova.git /root/nova
  - command: chdir=/root/nova git checkout stable/icehouse
  - command: chdir=/root/nova pip install -r requirements.txt
  - command: chdir=/root/nova python setup.py install

  - group: name=nova
  - user: name=nova groups=nova,libvirtd
  - file: path=/etc/nova state=directory owner=nova group=nova mode=0755
  - file: path=/var/log/nova state=directory owner=nova group=nova mode=0755
  - file: path=/var/lib/nova state=directory owner=nova group=nova mode=0755
  - file: path=/var/lib/nova/instances state=directory owner=nova group=nova mode=0755

  - template: src=compute01_files/nova.conf dest=/etc/nova/nova.conf
  - template: src=compute01_files/nova-compute.conf dest=/etc/nova/nova-compute.conf

  - file: path=/var/lib/nova/nova.sqlite state=absent

  - apt: pkg=python-libvirt
  - service: name=libvirt-bin state=restarted

  - template: src=compute01_files/initd_novacompute dest=/etc/init.d/nova-compute owner=root group=root mode=0755
  - service: name=nova-compute state=restarted enabled=yes



