#!/bin/sh
NAME=glance-api
DESC="Image API"
USERGROUP="glance:glance"
BINARY="/usr/bin/python /usr/local/bin/glance-api"

#Helper functions
start() {
        start-stop-daemon --start --quiet --background --make-pidfile \
                --pidfile /var/run/$NAME.pid --chuid $USERGROUP \
                --exec $BINARY
}

stop() {
        kill -9 $(ps aux | grep glance-api | grep -v grep | awk '{print $2}') && rm /var/run/$NAME.pid
}

case "$1" in
  start)
        echo -n "Starting $DESC: "
        start
        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
        stop
        echo "$NAME."
        ;;
  restart)
        echo -n "Restarting $DESC: "
        set +e
        stop
        set -e
        sleep 1
        start

        echo "$NAME."
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart}" >&2
        exit 1
        ;;
esac

exit 0